# Optimization exercise

The techniques I used here is still python scientific ecosystem: numpy, sci. For this optimization problem, you'd better reference: https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.minimize.htm.

In [1]:
import numpy as np
from scipy.optimize import minimize, rosen, rosen_der

# Input data.
R = np.array([51716.2, 65464, 85787.4, 155595.4])
q = np.array([9581284.6, 8609087.1, 8465419.9, 9132683.8, 11450758, 14639536, 20124378, 32034070, 44761640, 55131162, 68328234, 109028699, 124416368, 173170271])

lenR = R.shape[0]
itTimes = q.shape[0] - lenR - 1

# print lenR
# print itTimes
# print R
# print q

In [2]:
def optFun(x):
    res = 0.0
    for i in xrange(1, lenR + 1):
        tmp = x[0] * np.exp(0.26*i - 0.26)/(0.0622*np.exp(-R[i-1]/x[0]))
        # print 'tmp:', tmp
        
        for j in xrange(0, itTimes + 1):
            tmp -= q[i+j] * (1-x[1])**j / (1.0622**(j+1))
            # print tmp
            
        res += tmp ** 2
        
    return res

optFun((50000, 0.005))


2.9802840543335552e+17

Here, we must pay attention. From above test, we need to make the value of x[0] large enough, otherwise the value of `0.0622 * np.exp(-R[i-1]/x[0])` would be very large!

In [3]:
# Try lots of initial values instead of just one.
x0 = np.array([[50000, 0.005], [1000, 0.01], [2000, 0.0003]])

# cons = ({'type': 'ineq', 'fun': lambda x: x[0]},
#         {'type': 'ineq', 'fun': lambda x: x[1]},
#         {'type': 'ineq', 'fun': lambda x: 1 - x[1]})

bnds = ((0, None), (0, 1))

for i in xrange(x0.shape[0]):
    res = minimize(optFun, x0[i], method='SLSQP', bounds=bnds)
    print res
    print '\n'

     fun: 2.9802840543335552e+17
     jac: array([  1.27990025e+12,  -3.97118160e+18,   0.00000000e+00])
 message: 'Inequality constraints incompatible'
    nfev: 4
     nit: 1
    njev: 1
  status: 4
 success: False
       x: array([  5.00000000e+04,   5.00000000e-03])


     fun: 1.7312742971253578e+144
     jac: array([ -5.35288810e+143,   0.00000000e+000,   0.00000000e+000])
 message: 'Inequality constraints incompatible'
    nfev: 4
     nit: 1
    njev: 1
  status: 4
 success: False
       x: array([  1.00000000e+03,   1.00000000e-02])


     fun: 1.8458748102529868e+77
     jac: array([ -1.41757539e+76,   0.00000000e+00,   0.00000000e+00])
 message: 'Inequality constraints incompatible'
    nfev: 4
     nit: 1
    njev: 1
  status: 4
 success: False
       x: array([  2.00000000e+03,   3.00000000e-04])




C:\Anaconda2\lib\site-packages\scipy\optimize\slsqp.py:337: RuntimeWarning: invalid value encountered in greater
  bnderr = where(bnds[:, 0] > bnds[:, 1])[0]


In [4]:
# Use another method 'BFGS'.
# TODO: we can provide the first order derivative
#       of optFun for optimization function.

for i in xrange(len(x0)):
    # minimize(optFun,x0[i],method='bfgs', options={'disp':1})
    res = res = minimize(optFun, x0[i], method='BFGS', options={'gtol': 1e-6, 'disp': True})
    print res
    print '\n'

         Current function value: 298028405433355520.000000
         Iterations: 0
         Function evaluations: 24
         Gradient evaluations: 3
      fun: 2.9802840543335552e+17
 hess_inv: array([[1, 0],
       [0, 1]])
      jac: array([  1.27990025e+12,  -3.97118160e+18])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 24
      nit: 0
     njev: 3
   status: 2
  success: False
        x: array([  5.00000000e+04,   5.00000000e-03])


         Current function value: 1731274297125357832770158779095189638576538081933002006177032311529191891190137546093519634742912290120564924536629224853698116257939670228271104.000000
         Iterations: 0
         Function evaluations: 56
         Gradient evaluations: 11
      fun: 1.7312742971253578e+144
 hess_inv: array([[1, 0],
       [0, 1]])
      jac: array([ -5.35288810e+143,   0.00000000e+000])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 56
      nit: 0
     

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:11: RuntimeWarning: overflow encountered in double_scalars
C:\Anaconda2\lib\site-packages\scipy\optimize\optimize.py:562: RuntimeWarning: invalid value encountered in double_scalars
  grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]


# Compute Integration

In [169]:
# Pre-setting
import random
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [159]:
# Load MatLab m data File


import scipy.io

xMFile = scipy.io.loadmat('x.mat')
yMFile = scipy.io.loadmat('y.mat')
xx = xMFile['xx']
yy = yMFile['yy']


In [171]:
data = open('xx.txt', 'r').read()
xx = data.split('\n')
xx = np.array([float(x) for x in xx])
data = open('yy.txt', 'r').read()
yy = data.split('\n')
yy = np.array([float(y) for y in yy])

print xx 
print yy

[   2.   10.   10.   12.   15.   15.   15.   16.   16.   20.   21.   22.
   22.   24.   27.   27.   27.   33.   34.   35.   43.   46.   47.   47.
   48.   48.   49.   51.   51.   53.   53.   53.   54.   54.   54.   55.
   55.   55.   57.   58.   60.   61.   61.   61.   62.   64.   67.   68.
   68.   68.   69.   69.   69.   70.   77.   79.   81.   81.   84.   88.
   89.   91.   92.   92.   93.   95.   96.   98.  101.  102.  102.  102.
  103.  103.  105.  107.  107.  110.  111.  112.  112.  113.  114.  114.
  114.  117.  120.  120.  121.  121.  121.  122.  123.  123.  124.  124.
  124.  124.  125.  126.  127.  127.  128.  132.  133.  133.  134.  135.
  135.  136.  136.  137.  137.  137.  137.  137.  137.  140.  140.  142.
  143.  143.  143.  143.  143.  145.  145.  145.  146.  146.  146.  147.
  147.  148.  149.  149.  150.  151.  151.  155.  155.  156.  156.  156.
  156.  156.  157.  158.  158.  158.  159.  160.  160.  160.  160.  162.
  164.  165.  166.  170.  175.  177.  178.  178.  1

In [164]:
a1 = np.array([[2, 3], [3, 7]])
print np.dot(a1, a1)
print a1.dot(a1.dot(a1))

[[13 27]
 [27 58]]
[[107 228]
 [228 487]]


In [165]:
def Log_p_eta_given_y(x, y, eta):
    
    DF = np.exp(-(x / 360.0) * (y / 100.0))
    N = len(x)
    
    t = np.unique(x)
    n = len(t)
    t_head = t[1:]
    t_tail = t[:-1]
    h = t_head - t_tail
    h = np.insert(h, 0, 0)
    
    w = np.zeros((n, 1))
    y_bar = np.zeros((n, 1))
    SSE = 0.0
    
    for j in range(n):
        w[j] = np.sum(x == t[j])
        y_bar[j] = np.sum((x == t[j]) * DF) / w[j]
        SE = (x == t[j]) * (DF - y_bar[j])
        SSE += sum(SE ** 2)
        
    Q_prime = np.zeros((n-2, n))
    T_Col_N = n - 1
    T_m = np.zeros((n-2, T_Col_N))
    
    for j in range(n-2):
        Q_prime[j, j] = (h[j + 1] + 0.0) ** (-1)
        Q_prime[j, j + 2] = (h[j + 2] + 0.0) ** (-1)
        Q_prime[j, j + 1] = -(Q_prime[j, j] + Q_prime[j, j + 2])
        
        T_m[j, j] = (h[j + 1] + h[j + 2]) / 6.0
        T_m[j, j + 1] = h[j + 2] / 6.0
        
    maskT = range(T_Col_N)
    del maskT[-2]
    T_m = T_m[:, maskT]
    T_m = T_m + T_m.T
    W = np.diag([x[0] for x in w]) # np.diag(w)
    Q = Q_prime.T
    A = Q.dot(np.linalg.inv(T_m)).dot(Q.T)
    
    
    log_p_eta = -2 * np.log(1 + eta)
    p = 2
    log_1 = ((n - p) / 2.0) * np.log(eta)
    log_3 = ((N - p) / 2.0) * np.log(y_bar.T.dot(W - W.dot(np.linalg.inv(W + eta * A)).dot(W)).dot(y_bar) + SSE)
    
    
    if eta > 1:
        log_2 = 0.5 * n * np.log(eta) + 0.5 * np.log(np.linalg.det(W / eta + A))
    else:
        log_2 = 0.5 * np.log(np.linalg.det(W + eta * A))
    
    return log_p_eta + log_1 - log_2 - log_3

In [166]:
print xx.shape
print yy.shape
print Log_p_eta_given_y(xx, yy, 0.3)

(317L,)
(317L,)
[[ 868.20796415]]


In [174]:
Log_p_eta_given_y(xx, yy, 0.0001)

array([[ 300.00236633]])

In [179]:
from scipy import integrate


invexp = lambda eta: (Log_p_eta_given_y(xx, yy, eta))
y, err = integrate.quad(invexp, 0.01, np.inf)

In [180]:
print y
print err


-4525.01225094
2411.54307216
