# Optimization exercise

The techniques I used here is still python scientific ecosystem: numpy, sci. For this optimization problem, you'd better reference: https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.minimize.htm.

In [1]:
import numpy as np
from scipy.optimize import minimize, rosen, rosen_der

# Input data.
R = np.array([51716.2, 65464, 85787.4, 155595.4])
q = np.array([9581284.6, 8609087.1, 8465419.9, 9132683.8, 11450758, 14639536, 20124378, 32034070, 44761640, 55131162, 68328234, 109028699, 124416368, 173170271])

lenR = R.shape[0]
itTimes = q.shape[0] - lenR - 1

# print lenR
# print itTimes
# print R
# print q

In [2]:
def optFun(x):
    res = 0.0
    for i in xrange(1, lenR + 1):
        tmp = x[0] * np.exp(0.26*i - 0.26)/(0.0622*np.exp(-R[i-1]/x[0]))
        # print 'tmp:', tmp
        
        for j in xrange(0, itTimes + 1):
            tmp -= q[i+j] * (1-x[1])**j / (1.0622**(j+1))
            # print tmp
            
        res += tmp ** 2
        
    return res

optFun((50000, 0.005))


2.9802840543335552e+17

Here, we must pay attention. From above test, we need to make the value of x[0] large enough, otherwise the value of `0.0622 * np.exp(-R[i-1]/x[0])` would be very large!

In [3]:
# Try lots of initial values instead of just one.
x0 = np.array([[50000, 0.005], [1000, 0.01], [2000, 0.0003]])

# cons = ({'type': 'ineq', 'fun': lambda x: x[0]},
#         {'type': 'ineq', 'fun': lambda x: x[1]},
#         {'type': 'ineq', 'fun': lambda x: 1 - x[1]})

bnds = ((0, None), (0, 1))

for i in xrange(x0.shape[0]):
    res = minimize(optFun, x0[i], method='SLSQP', bounds=bnds)
    print res
    print '\n'

     fun: 2.9802840543335552e+17
     jac: array([  1.27990025e+12,  -3.97118160e+18,   0.00000000e+00])
 message: 'Inequality constraints incompatible'
    nfev: 4
     nit: 1
    njev: 1
  status: 4
 success: False
       x: array([  5.00000000e+04,   5.00000000e-03])


     fun: 1.7312742971253578e+144
     jac: array([ -5.35288810e+143,   0.00000000e+000,   0.00000000e+000])
 message: 'Inequality constraints incompatible'
    nfev: 4
     nit: 1
    njev: 1
  status: 4
 success: False
       x: array([  1.00000000e+03,   1.00000000e-02])


     fun: 1.8458748102529868e+77
     jac: array([ -1.41757539e+76,   0.00000000e+00,   0.00000000e+00])
 message: 'Inequality constraints incompatible'
    nfev: 4
     nit: 1
    njev: 1
  status: 4
 success: False
       x: array([  2.00000000e+03,   3.00000000e-04])




C:\Anaconda2\lib\site-packages\scipy\optimize\slsqp.py:337: RuntimeWarning: invalid value encountered in greater
  bnderr = where(bnds[:, 0] > bnds[:, 1])[0]


In [4]:
# Use another method 'BFGS'.
# TODO: we can provide the first order derivative
#       of optFun for optimization function.

for i in xrange(len(x0)):
    # minimize(optFun,x0[i],method='bfgs', options={'disp':1})
    res = res = minimize(optFun, x0[i], method='BFGS', options={'gtol': 1e-6, 'disp': True})
    print res
    print '\n'

         Current function value: 298028405433355520.000000
         Iterations: 0
         Function evaluations: 24
         Gradient evaluations: 3
      fun: 2.9802840543335552e+17
 hess_inv: array([[1, 0],
       [0, 1]])
      jac: array([  1.27990025e+12,  -3.97118160e+18])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 24
      nit: 0
     njev: 3
   status: 2
  success: False
        x: array([  5.00000000e+04,   5.00000000e-03])


         Current function value: 1731274297125357832770158779095189638576538081933002006177032311529191891190137546093519634742912290120564924536629224853698116257939670228271104.000000
         Iterations: 0
         Function evaluations: 56
         Gradient evaluations: 11
      fun: 1.7312742971253578e+144
 hess_inv: array([[1, 0],
       [0, 1]])
      jac: array([ -5.35288810e+143,   0.00000000e+000])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 56
      nit: 0
     

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:11: RuntimeWarning: overflow encountered in double_scalars
C:\Anaconda2\lib\site-packages\scipy\optimize\optimize.py:562: RuntimeWarning: invalid value encountered in double_scalars
  grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]


# Compute Integration

In [1]:
# Pre-setting
import random
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [8]:
# Load MatLab m data File

import scipy.io

xMFile = scipy.io.loadmat('x.mat')
yMFile = scipy.io.loadmat('y.mat')
xx = xMFile['xx']
yy = yMFile['yy']

In [21]:
a1 = np.array([[1], [3], [3], [1], [2], [2]])
print a1.shape
a1 = np.insert(a1, 0, 0)
print a1.shape

(6L, 1L)
(7L,)


In [26]:
print a1
print a1 ** 2

[0 1 3 3 1 2 2]
[0 1 9 9 1 4 4]


In [34]:
b = range(7)
print b
del b[-2]
print b

[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 6]


In [41]:
c = np.array([[2, 3, 5], [12, 11, 10]])
print c
print c.T
print c[:, [0, 2]]
print np.diag([3, 2, 2])
print np.log(4)

[[ 2  3  5]
 [12 11 10]]
[[ 2 12]
 [ 3 11]
 [ 5 10]]
[[ 2  5]
 [12 10]]
[[3 0 0]
 [0 2 0]
 [0 0 2]]
1.38629436112


In [108]:
a1 = np.array([2, 3, 4])
a1[1] ** (-1)

0.33333333333333331

In [157]:
def Log_p_eta_given_y(x, y, eta):
    
    DF = np.exp(-(x / 360.0) * (y / 100.0))
    N = len(x)
    
    t = np.unique(x)
    n = len(t)
    t_head = t[1:]
    t_tail = t[:-1]
    h = t_head - t_tail
    h = np.insert(h, 0, 0)
    print 'h'
    print h
    
    w = np.zeros((n, 1))
    y_bar = np.zeros((n, 1))
    SSE = 0.0
    
    for j in range(n):
        w[j] = np.sum(x == t[j])
        y_bar[j] = np.sum((x == t[j]) * DF) / w[j]
        SE = (x == t[j]) * (DF - y_bar[j])
        SSE += sum(SE ** 2)
        
    Q_prime = np.zeros((n-2, n))
    T_Col_N = n - 1
    T_m = np.zeros((n-2, T_Col_N))
    
    for j in range(n-2):
        Q_prime[j, j] = (h[j + 1] + 0.0) ** (-1)
        Q_prime[j, j + 2] = (h[j + 2] + 0.0) ** (-1)
        Q_prime[j, j + 1] = -(Q_prime[j, j] + Q_prime[j, j + 2])
        
        T_m[j, j] = (h[j + 1] + h[j + 2]) / 6.0
        T_m[j, j + 1] = h[j + 2] / 6.0
        
    print 'h ** -1'
    print h[1]
    print ((h[1] + 0.0) ** (-1))
    print 'Q_prime:'
    print Q_prime
    maskT = range(T_Col_N)
    del maskT[-2]
    T_m = T_m[:, maskT]
    T_m = T_m + T_m.T
    W = np.diag([x[0] for x in w]) # np.diag(w)
    Q = Q_prime.T
    A = Q.dot(np.linalg.inv(T_m)).dot(Q.T)
    
    
    log_p_eta = -2 * np.log(1 + eta)
    p = 2
    log_1 = ((n - p) / 2.0) * np.log(eta)
    print 'check:'
    print W
    log_3 = ((N - p) / 2.0) * np.log(SSE + y_bar.T.dot(W - W.dot(np.linalg.inv(eta * A + W)).dot(W).dot(W)).dot(y_bar))
    
    if eta > 1:
        log_2 = 0.5 * n * np.log(eta) + 0.5 * np.log(np.linalg.det(W / eta + A))
    else:
        log_2 = 0.5 * np.log(np.linalg.det(W + eta * A))
        
    return log_p_eta + log_1 - log_2 - log_3

In [158]:
print xx.shape
print yy.shape
Log_p_eta_given_y(xx, yy, 0.3)

(317L, 1L)
(317L, 1L)
h
[ 0  8  2  3  1  4  1  1  2  3  6  1  1  8  3  1  1  1  2  2  1  1  2  1  2
  1  1  2  3  1  1  1  7  2  2  3  4  1  2  1  1  2  1  2  3  1  1  2  2  3
  1  1  1  1  3  3  1  1  1  1  1  1  1  1  4  1  1  1  1  1  3  2  1  2  1
  1  1  1  1  1  4  1  1  1  1  1  2  2  1  1  4  5  2  1  3  1  1  8  1  1
  2  1  1  2  1  1  1  2  1  1  3  1  1  2  1  1  1  1  1  1  1  3  1  1  4
  1  1  1  1  2  1  1  4  1  1  6  1  1  1  1  1  1  1  1  1  2  2  1  1  1
  2  1 10  9  6 11  6  7  1  6  2  4  7  5  1 14 11  3]
h ** -1
8
0.125
Q_prime:
[[ 0.125      -0.625       0.5        ...,  0.          0.          0.        ]
 [ 0.          0.5        -0.83333333 ...,  0.          0.          0.        ]
 [ 0.          0.          0.33333333 ...,  0.          0.          0.        ]
 ..., 
 [ 0.          0.          0.         ...,  0.07142857  0.          0.        ]
 [ 0.          0.          0.         ..., -0.16233766  0.09090909  0.        ]
 [ 0.          0.          0.   

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:56: RuntimeWarning: invalid value encountered in log


array([[ nan]])